---
name: test_nornir_napalm
on: [push,pull_request]

jobs:
  linters:
    name: linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: '3.11'
          enable-cache: true

      - name: Install Dependencies
        run: uv sync --locked

      - name: Run ruff
        run: make ruff
      - name: Run format
        run: make format
      - name: Run mypy
        run: make mypy

  pytest:
    name: Testing on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install Dependencies
        run: uv sync --locked

      - name: Run pytest
        run: make pytest

#   release:
#     name: Releasing to pypi
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@master
#       - name: Build
#         uses: abatilo/actions-poetry@v1.5.0
#         with:
#           python_version: 3.8.0
#           poetry_version: 1.0
#           working_directory: .
#           args: build
#       - name: Publish package
#         if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
#         uses: pypa/gh-action-pypi-publish@master
#         with:
#           user: __token__
#           password: ${{ secrets.pypi_password }}
